default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: mynder_development

test:
  <<: *default
  database: mynder_test

production:
  <<: *default
  database: mynder_production
  username: mynder
  password: <%= ENV['MYNDER_DATABASE_PASSWORD'] %>
