# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 806a49f846c58ab86aa0e487b796b99740986971b876b2ce4a52641b47a0783c2df8fa8a8fe8f507af9c08878081fd78542873548ca44e7d52a61f0b49282184

test:
  secret_key_base: c4e82436560ce40f82abf6e53f18c1559b4ab75916d0725a173fa660785b864a699f25f610f65be1ab02a423bf284a828d94545e86fe2b62cf5ee44d818a6b4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
